[package]
name = "paper-rage"
description = "Easy and secure paper backups of secrets"
version = "0.1.0"
edition = "2021"
authors = ["Matias Korhonen <me@matiaskorhonen.fi"]
license = "MIT"
categories = ["command-line-utilities", "cryptography"]

[dependencies.age]
version = "0.9.0"
features = ["armor"]
